version: "3"
services:
  backend:
    build: .
    ports:
    - "8080:8080"
    environment:
      hostname: "http://docker.for.mac.host.internal:4001"
      channel: "mychannel"
      chaincode: "emrcc"
      chaincodeVer: "v1"
      