apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moei-backend-deployment
spec:
  selector:
    matchLabels: 
      app: moei
  replicas: 1
  template:
    metadata:
      labels:
        app: moei
    spec:
      containers:
      - name: backend
        image: schmidtp0740/moei_backend:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      - name: console
        image: schmidtp0740/moei_console:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3001